### ISSUE TITLE
ImageNode not rendering full image

### ISSUE THREAD

**Issue by andreas-umbricht** [SceneView/sceneview-android#390]
I used the samples/ar-model-viewer-compose project and made some small changes. Instead of using a ModelNode I wanted to try out an ImageNode.
```
    fun createAnchorNode(
        engine: Engine,
        materialLoader: MaterialLoader,
        anchor: Anchor
    ): AnchorNode {
        val anchorNode = AnchorNode(engine = engine, anchor = anchor)

        val imageNode = ImageNode(
            materialLoader = materialLoader,
            imageResId = R.drawable.img_1,
            normal = Direction(0f)
        ).apply {
            transform(
                position = Position(
                    this.position.x,
                    this.position.y + 1.6f,
                    this.position.z - 2f
                )
            )
        }

        anchorNode.addChildNode(imageNode)

        return anchorNode
    }
```

The Image should be pointing at the camera and be located in mid air. This totally works but there is a huge problem/bug while rendering.

![Screenshot_20240111_170945](https://github.com/SceneView/sceneview-android/assets/79219553/dd802aaf-612a-49e3-8796-d316236db523)

As you can see, the image is diagonally cut in half. I tried with multiple files and it always resulted with the same problem.

**Comment by Swithurn** [comment]
Also having same issue, image is diagonally cut in half.

**Comment by JeromeCHA** [comment]
I opened an issue https://github.com/SceneView/sceneview-android/issues/379 3 weeks ago and it should be fixed on next version PR : https://github.com/SceneView/sceneview-android/pull/392

**Comment by nallaperumal** [comment]
Me too facing the same issue. Please also help me if we can create a textnode to place text content and any sample code for the same.

**Comment by ryust** [comment]
Was this "fixed" in 2.0.3 with #392? I am still experiencing similar shearing of models in the latest release.

**Comment by natasam** [comment]
It is not fixed yet, I am also getting half images when using ImageNode.

**Comment by ThomasGorisse** [comment]
Fixed in `2.0.4`

**Comment by ryust** [comment]
I'm not sure this is fixed or I have a different issue. In 2.0.4, I continue to see an occasional diagonal cutting off a ModelNode image when moving the camera around for a model with Google geospatial anchors.
